name:                mytcc
version:             0.1.0.0
github:              "Godalin/mytcc"
license:             BSD3
author:              "Godalin"
maintainer:          "1198080313@qq.com"
copyright:           "GPL3.0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Godalin/mytcc#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  mytcc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    dependencies:
    - mytcc

tests:
  mytcc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    dependencies:
    - mytcc
    - hspec
